site_name: IRenE Webapp Documentation
site_url: https://flechtenberg.github.io/irene-webapp/

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            # Add the project root to sys.path
            module_paths:
              - ..

nav:
  - Home: index.md
  - API:
      - Processing Module: processing.md
      - App Module: app.md
